const REQUIRED_DESKTOP_APP_VERSION = 200;
const REQUIRED_MOBILE_APP_VERSION = 0;
const MAX_FILE_STORAGE_DAYS = 21;

export {
  REQUIRED_DESKTOP_APP_VERSION,
  REQUIRED_MOBILE_APP_VERSION,
  MAX_FILE_STORAGE_DAYS,
};
